// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import ClipBoardController from "./clip_board_controller"
application.register("clip-board", ClipBoardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ProgressBarController from "./progress_bar_controller"
application.register("progress-bar", ProgressBarController)

import RangeSliderController from "./range_slider_controller"
application.register("range-slider", RangeSliderController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)
