meta_name: "Schwipe"
meta_title: "Swipe and choose with Schwipe!"
meta_description: "Can't decide on what to eat, watch or do with your friend(s)? Swipe individually through a stack of propositions to pick the one on which you matched!"
meta_image: "logo-noir.png"

